### ISSUE TITLE
This is good script. But....

### ISSUE THREAD

**Issue by ZohaibRamzan** [pidugusundeep/Brat-and-snorkel#2]
This is good script. But main thing is to convert .txt file to IOB tagged(CoNLL) format by using .ann file data for which i am looking for.

**Comment by Mahmedturk** [comment]
@ZohaibRamzan were you able to find a script that converts .ann and .txt file to CONLL format?

**Comment by ZohaibRamzan** [comment]
No I wrote the code by myself
